### PR TITLE
Add the blahaj AUR packages to the installation instructions

### PR DESCRIPTION
**Pull request by Antiz96**
Hi,

Thanks for your great work with `blahaj`!
I added it to the [Arch User Repository](https://wiki.archlinux.org/title/Arch_User_Repository), I hope it's okay for you :)

I submitted the [blahaj](https://aur.archlinux.org/packages/blahaj) AUR package (which is built from source against the latest tagged release, see the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=blahaj)), as well as the [blahaj-git](https://aur.archlinux.org/packages/blahaj-git) AUR package (which is built from source against the latest commit to the main branch, see the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=blahaj-git)).
I'm obviously down to maintain those two packages for the future releases of `blahaj` :wink: 

This PR aims to update the installation instructions accordingly.
I remain available if you need any additional information :smile:

### CODE REVIEW

**Comment by GeopJr** [comment]
LGTM and thanks for packaging blahaj! I didn't expect this silly little tool to be packaged :sweat_smile: 

~~You should probably run test_mt to match the build~~ nvm you did it already!

*Heads up: I'll make a new release in a few minutes*

**Comment by Antiz96** [comment]
Alright, I'll wait for the new release and update both PKGBUILDs according to https://github.com/GeopJr/BLAHAJ/pull/5 then ;)

**Comment by GeopJr** [comment]
Done!

**Comment by Antiz96** [comment]
Done as well:
blahaj --> https://aur.archlinux.org/cgit/aur.git/commit/?h=blahaj&id=ac71645e47765ddeaf382de3a68a982fcdb0b803
blahaj-git --> https://aur.archlinux.org/cgit/aur.git/commit/?h=blahaj-git&id=6794b7a91c37b5060882f065aa7366a6255d6908

**Pull request merged**
